// <auto-generated />
using System;
using CaseXP.Services.ProdutoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseXP.Services.ProdutoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240627213914_AddProdutoAndSeeds")]
    partial class AddProdutoAndSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseXP.Services.ProdutoAPI.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<double>("AplicacaoMinima")
                        .HasColumnType("float");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiasLiquidez")
                        .HasColumnType("int");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TaxaAdm")
                        .HasColumnType("float");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            IdProduto = 1,
                            AplicacaoMinima = 5000.0,
                            DataVencimento = new DateOnly(2026, 6, 1),
                            Descricao = "Fundo de Investimento em ativos de FII e ações com dividendos",
                            DiasLiquidez = 365,
                            NivelRisco = "Médio",
                            NomeProduto = "Fundo de Investimentos X1",
                            TaxaAdm = 1.5
                        },
                        new
                        {
                            IdProduto = 2,
                            AplicacaoMinima = 10000.0,
                            DataVencimento = new DateOnly(2028, 12, 1),
                            Descricao = "Fundo CDB 120% CDI",
                            DiasLiquidez = 720,
                            NivelRisco = "Baixo",
                            NomeProduto = "Fundo Renda Fixa X2",
                            TaxaAdm = 1.2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
