// <auto-generated />
using CaseXP.Services.CupomAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseXP.Services.CupomAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240625010715_SeedCupomTables")]
    partial class SeedCupomTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseXP.Services.CupomAPI.Models.Cupom", b =>
                {
                    b.Property<int>("IdCupom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCupom"));

                    b.Property<string>("CodigoCupom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<int>("ValorMinimo")
                        .HasColumnType("int");

                    b.HasKey("IdCupom");

                    b.ToTable("Cupons");

                    b.HasData(
                        new
                        {
                            IdCupom = 1,
                            CodigoCupom = "5OFF",
                            Desconto = 5.0,
                            ValorMinimo = 20
                        },
                        new
                        {
                            IdCupom = 2,
                            CodigoCupom = "10OFF",
                            Desconto = 10.0,
                            ValorMinimo = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
