// <auto-generated />
using System;
using CaseXP.Services.ProdutoDisponivelAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseXP.Services.ProdutoDisponivelAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240627215249_AddProdutoDisponivelAndSeeds")]
    partial class AddProdutoDisponivelAndSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseXP.Services.ProdutoDisponivelAPI.Models.ProdutoDisponivel", b =>
                {
                    b.Property<int>("IdProdutoDisponivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdutoDisponivel"));

                    b.Property<DateOnly>("DataFimVenda")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicioVenda")
                        .HasColumnType("date");

                    b.Property<int>("IdGrupoPublicoAlvoProduto")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioResponsavelProduto")
                        .HasColumnType("int");

                    b.Property<double>("TaxaAdm")
                        .HasColumnType("float");

                    b.HasKey("IdProdutoDisponivel");

                    b.ToTable("ProdutosDisponiveis");

                    b.HasData(
                        new
                        {
                            IdProdutoDisponivel = 1,
                            DataFimVenda = new DateOnly(2024, 6, 30),
                            DataInicioVenda = new DateOnly(2024, 6, 1),
                            IdGrupoPublicoAlvoProduto = 10,
                            IdProduto = 1,
                            IdUsuarioResponsavelProduto = 50,
                            TaxaAdm = 1.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
